---
- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  selinux:
    state: disabled

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].* swap .*)$'
    replace: '# \1'

- name: sysctl.conf
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      vm.swappiness = 0
    dest: /etc/sysctl.d/k8s.conf
  register: sysctl_k8s_conf

- name: update sysctl
  shell: sysctl --system
  when: sysctl_k8s_conf.changed
