---
# install software

- name: Install epel-release
  yum:
    name:
      - epel-release
    state: installed

- name: Remove rpms may conflict
  yum:
    name:
      - docker
      - docker-cli
      - docker-client
      - docker-engine
      - docker-common
    state: removed

- name: Install software
  yum:
    name:
      - docker-ce
    state: installed