---
# install software

- name: Install epel-release
  yum:
    name:
      - epel-release
    state: latest

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Remove rpms may conflict
  yum:
    name:
      - docker
      - docker-cli
      - docker-client
      - docker-engine
      - docker-common
    state: removed

- name: Install software
  yum:
    name:
      - docker-ce
      - kubelet
    state: latest