---
# install software

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Remove rpms may conflict
  yum:
    name:
      - docker-ce
      - docker-ce-cli
    state: removed

- name: Install all software
  yum:
    name:
      - docker
      - kubelet
    state: installed